### ISSUE TITLE
background

### ISSUE THREAD

**Issue by marcosci** [Thell/ccloutline#1]
Hi @Thell,

very interesting package, nice work there.
Just one short question: Is it possible to set a background value for the labeling?
For example in your README, to not label zero?

Cheers
Marco

**Comment by Thell** [comment]
If you're referring to the plot image sure. Its just a ggvis generated plot grabbing the positioning info from the connected components so they _could_ be whatever you desire.
As for the connected components themselves you wouldn't alter the connection label.

**Comment by marcosci** [comment]
No, I was talking about the connected components. 
The way I am using your code right now is to have a filter matrix afterwards, to set the connected component that consisted of the 0s to NA.

As an example:
![image](https://user-images.githubusercontent.com/10864574/39872344-f4715a08-5467-11e8-84bb-b4eeef934508.png)

The first image is the matrix I wish to label, but it would be nice to get only values for 0.5 (yellowish color) and set the other values as background/NA/whatever. The second image is how it works right now, and the last one how I know some other CCL algorithm work: They only label a certain value and set the remaining body of the matrix to NA.

I am totally lacking your cpp expertise - if it's not possible at all, just close here 😃

**Comment by Thell** [comment]
What you desire for the output is indeed the visualization and your method of a 'filter matrix' to mask out based on an original threshold value after identifying the *connected* components would be the way to go.

The ccl code would only label *connected* components identically.

Even if the original data is pre-treated so that any values above and below the threshold range are set to the same value you'd still have disconnected islands which would get _labelled_ as a distinct _connected component_.
