### ISSUE TITLE
4-way connected labeling

### ISSUE THREAD

**Issue by mhesselbarth** [Thell/ccloutline#2]
Hey @Thell, 

would it be somehow possible to tweak the algorithm that only 4-way connected labeling is possible? 

I had the idea to somehow change the following line in a way that instead of N, NW, W, SW, S, SE, E and NE only 4 N, W, S, and E geht a value, whereas all other directions get a 0. 

` const border_t N(1), NW(2), W(4), SW(8), S(16), SE(32), E(64), NE(128); `

**Comment by Thell** [comment]
Using ccloutline for 4-way connected components would be counter productive since it is specifically designed to reduce computation times of the diagonals. There are already existing implementations of 4-way connected component labeling with R interfaces that are efficient. I'd look into those prior to attempting to modify this implementation.

**Comment by mhesselbarth** [comment]
I already guessed that this would be the case. Anyways, thank you very much for your help and suggestions! 

Btw, ccloutline is really great :) !
